spring:
  application:
    name: spring_8secu
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: c##idev
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update  #create 면 안됨 create는 실행하면 다시 초기화 후 시작하기에 DB저장값 날라감
    properties:
      hibernate:
        '[format_sql]': true
logging:
  level:
    '[org.iclass.secu1]': DEBUG
    '[org.springframework.security]': DEBUG
  pattern:
    console: '%clr(%-5level){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n'
server:
  port: 8080
  